name: Cross-Platform Build

on:
  workflow_dispatch:
  push:
    paths: ['src/**', '.github/workflows/build.yml']
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev
        fi
      shell: bash

    - name: Build
      run: |
        git clean -fdx
        git submodule foreach --recursive git clean -fdx
        git reset --hard
        git submodule foreach --recursive git reset --hard
        git submodule update --init --recursive
        cd src
        make

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jumping-runner
        path: src
