name: Release Jar

permissions:
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      # Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Extract the project version from gradle.properties
      - name: Get Project Version
        id: get_version
        run: |
          VERSION=$(grep "^projectVersion=" gradle.properties | cut -d'=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Check if it's a pre-release
      - name: Check if Pre-release
        id: check_prerelease
        run: |
          if [[ "${{ env.VERSION }}" == *"-pre" ]]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi

      # Define the JAR file path based on the version
      - name: Set JAR Path
        id: set_jar_path
        run: |
          JAR_PATH="./lwjgl3/build/libs/Jumping Runner-${{ env.VERSION }}.jar"
          if [[ -f "$JAR_PATH" ]]; then
            echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
          else
            echo "Error: $JAR_PATH does not exist." >&2
            exit 1
          fi

      # Create GitHub Release using idev-coder/github-actions-release
      - name: Create GitHub Release
        uses: idev-coder/github-actions-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: "${{ env.VERSION }}"
          name: "${{ env.VERSION }}"
          body: "${{ env.VERSION }}"
          draft: 'false'
          prerelease: "${{ env.PRERELEASE }}"
          repo: "https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

      # Upload the .jar file to the release
      - name: Upload Release Asset
        uses: sekwah41/upload-release-assets@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
          asset_path: "${{ env.JAR_PATH }}"
          asset_name: "Jumping-Runner.jar"
          asset_content_type: application/java-archive
