name: Release Jar

permissions:
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      # Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Extract the project version from gradle.properties
      - name: Get Project Version
        id: get_version
        run: |
          VERSION=$(grep "^projectVersion=" gradle.properties | cut -d'=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Check if it's a pre-release
      - name: Check if Pre-release
        id: check_prerelease
        run: |
          if [[ "${{ env.VERSION }}" == *"-pre" ]]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi

      # Create a new GitHub release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.VERSION }}"
          name: "${{ env.VERSION }}"  # Replaces `release_name` with `name`
          prerelease: "${{ env.PRERELEASE }}"

      # Upload the .jar file to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: "./lwjgl3/build/libs/*.jar"
          asset_name: "Jumping-Runner.jar" # Optionally customize the name
          asset_content_type: application/java-archive
