name: Release Jar

permissions:
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      # Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Extract the project version from gradle.properties
      - name: Get Project Version
        id: get_version
        run: |
          VERSION=$(grep "^projectVersion=" gradle.properties | cut -d'=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Determine if the version is a pre-release by checking for `-pre`
      - name: Check if Pre-release
        id: check_prerelease
        run: |
          if [[ "${{ env.VERSION }}" == *"-pre" ]]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.VERSION }}"
          name: "${{ env.VERSION }}"  # Replaces `release_name` with `name`
          prerelease: "${{ env.PRERELEASE }}"
          files: "lwjgl3/build/libs/*.jar"
