name: Linux
on:
  workflow_dispatch:
  push:
    paths: ['src/**', '.github/workflows/linux.yml']
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64, arm64]
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      ARCH: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          sudo apt-get install -y libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev

      - name: Build Project
        run: |
          cd src
          make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=STATIC ARCH=${{ matrix.arch }}

      - name: Package
        run: |
          mkdir release
          cp src/${{ env.PROJECT_NAME }} release/
          cp -r resources release/
          7z a ${{ env.PROJECT_NAME }}_linux_${{ matrix.arch }}.zip ./release/*
