name: macOS
on:
  workflow_dispatch:
  push:
    paths: ['src/**', '.github/workflows/macos.yml']
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64, arm64]
    runs-on: macos-latest
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      ARCH: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Project
        run: |
          cd src
          make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=STATIC ARCH=${{ matrix.arch }}

      - name: Package
        run: |
          mkdir -p release/${{ env.PROJECT_NAME }}.app/Contents/MacOS
          cp src/${{ env.PROJECT_NAME }} release/${{ env.PROJECT_NAME }}.app/Contents/MacOS/
          cp -r resources release/${{ env.PROJECT_NAME }}.app/Contents/
          7z a ${{ env.PROJECT_NAME }}_macos_${{ matrix.arch }}.zip ./release/*
