name: macOS
on:
  workflow_dispatch:
  push:
    paths: ['src/**', '.github/workflows/macos.yml']
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_BUILD_PATH: ${{ github.event.repository.name }}/src
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_macos_${{ matrix.arch }}
      PROJECT_RESOURCES_PATH: resources
      RAYLIB_PATH: src/external/raylib/src

    steps:
      - name: Checkout this repo
        uses: actions/checkout@master
        with:
          path: ${{ env.PROJECT_NAME }}

      - name: Setup Release Paths
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          echo "PROJECT_RELEASE_PATH=${{ env.PROJECT_NAME }}_v${{ github.event.release.tag_name }}_macos_${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Setup Environment
        run: |
          mkdir -p ${{ env.PROJECT_RELEASE_PATH }}/${{ env.PROJECT_NAME }}.app/Contents/{MacOS,Resources}

      - name: Build Project
        run: |
          cd ${{ env.PROJECT_BUILD_PATH }}
          make PLATFORM=PLATFORM_DESKTOP BUILD_MODE=RELEASE RAYLIB_LIBTYPE=STATIC RAYLIB_PATH=${{ env.RAYLIB_PATH }} ARCH=${{ matrix.arch }}

      - name: Generate Artifacts
        run: |
          cp ${{ env.PROJECT_BUILD_PATH }}/${{ env.PROJECT_NAME }} ${{ env.PROJECT_RELEASE_PATH }}/${{ env.PROJECT_NAME }}.app/Contents/MacOS/
          cp ${{ env.PROJECT_NAME }}/src/${{ env.PROJECT_NAME }}.icns ${{ env.PROJECT_RELEASE_PATH }}/${{ env.PROJECT_NAME }}.app/Contents/Resources/
          cp ${{ env.PROJECT_NAME }}/src/Info.plist ${{ env.PROJECT_RELEASE_PATH }}/${{ env.PROJECT_NAME }}.app/Contents/
          cp -r ${{ env.PROJECT_NAME }}/${{ env.PROJECT_RESOURCES_PATH }} ${{ env.PROJECT_RELEASE_PATH }}/${{ env.PROJECT_NAME }}.app/Contents/
          cp ${{ env.PROJECT_NAME }}/README.md ${{ env.PROJECT_RELEASE_PATH }}/
          cp ${{ env.PROJECT_NAME }}/LICENSE ${{ env.PROJECT_RELEASE_PATH }}/
          7z a ./${{ env.PROJECT_RELEASE_PATH }}.zip ./${{ env.PROJECT_RELEASE_PATH }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_RELEASE_PATH }}.zip
          path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

      - name: Upload Artifact to Release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PROJECT_RELEASE_PATH }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
