name: Windows
on:
  workflow_dispatch:
  push:
    paths: ['src/**', '.github/workflows/windows.yml']
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64, arm64]
    runs-on: windows-latest
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      ARCH: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2

      - name: Build Project
        run: |
          cd src
          make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=STATIC ARCH=${{ matrix.arch }}

      - name: Package
        run: |
          mkdir release
          cp src/${{ env.PROJECT_NAME }}.exe release/
          cp -r resources release/
          7z a ${{ env.PROJECT_NAME }}_windows_${{ matrix.arch }}.zip ./release/*
